title: Plana 的笔记
author:
  name: Plana
  email: plana@schale.net

description: |
  欢迎访问 Plana 的个人笔记！

sass:
  quiet_deps: true
  silence_deprecations: [import]

plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima

minima:
  skin: auto
  date_format: "%Y-%m-%d"
  show_excerpts: false

  nav_pages:
    - about.md

  social_links:
    - title: Plana (@planadesu)
      icon: github
      url: "https://github.com/planadesu"
