title: Plana 的笔记
author:
  name: Plana
  email: plana@schale.net

description: |
  欢迎访问 Plana 的个人笔记！

plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima

minima:
  skin: auto
  date_format: "%Y-%m-%d"

  social_links:
    - title: Plana (@planadesu)
      icon: github
      url: "https://github.com/planadesu"
